# Generated by Django 5.0.6 on 2024-05-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosusermodel',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=50, verbose_name='Estado'),
        ),
    ]
