# Generated by Django 5.0.6 on 2024-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todosusermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todosusermodel',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
