# Generated by Django 5.0.6 on 2024-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todosusermodel_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosusermodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='todosusermodel',
            name='due_date',
            field=models.DateField(blank=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='todosusermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='todosusermodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo'),
        ),
    ]
